### ISSUE TITLE
Error in api_imageupload migration

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#148]
Hi @vsoch ,

is there a way to fix this? or I should go back to previous sregistry version?

```
WARNING Database disabled. Install sqlalchemy for full functionality
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, djcelery, logs, main, sessions, social_django, taggit, users
Running migrations:
  Applying api.0002_auto_20180911_0335...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "api_imageupload" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 515, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 684, in _alter_field
    params,
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "api_imageupload" does not exist

root@5ad7f44d01c4:/code# python manage.py collectstatic --noinput

0 static files copied to '/var/www/static', 287 unmodified.
root@5ad7f44d01c4:/code# python manage.py makemigrations api_imageupload
WARNING Database disabled. Install sqlalchemy for full functionality
App 'api_imageupload' could not be found. Is it in INSTALLED_APPS?
```

Thanks in advance! ;)

**Comment by vsoch** [comment]
hey @victorsndvg ! This looks like an order of operations thing for the migrations. It's telling you a field (Image --> image upload) doesn't exist. I would try to do `python manage.py migrate api` first, and then the commands again.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

the error is still there. I can share how a particular DB table looks like, if you want more info...

Thanks for the quick response!

**Comment by vsoch** [comment]
Do you have a migrations folder in the shub/api folder?

**Comment by vsoch** [comment]
and you did

```
python manage.py makemigrations api
```

**Comment by vsoch** [comment]
That command should compare your database with the migrations, and create needed ones.

**Comment by victorsndvg** [comment]
yep, this is the output:

```
# python manage.py makemigrations api
WARNING Database disabled. Install sqlalchemy for full functionality
Migrations for 'api':
  shub/apps/api/migrations/0026_auto_20180911_1032.py
    - Alter field upload_id on imageupload
```

**Comment by vsoch** [comment]
yes, that's what you want to see. Now try:

```
python manage.py migrate api
```

**Comment by victorsndvg** [comment]
Ok. It return the same error as in the original post.

I don't know if this is relevant, but this is the content of `0002_auto_xxxx_xxxx.py`:

```
# cat shub/apps/api/migrations/0002_auto_20180911_0335.py 
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='upload_id',
            field=models.CharField(default='675bd740f0a1466d89c8b515be28a67a', editable=False, max_length=32, unique=True),
        ),
    ]
```

**Comment by vsoch** [comment]
That is definitely missing quite a bit. The only thing I can think of to do is:
 
 1. backup that folder
 2. I'll give you the folder of migrations that I have (see attached below)
 3. Try running my migrations (`python manage.py migrate api`)

and if that doesn't work, remove all migrations and try making them again.
[app-api-migrations.tar.gz](https://github.com/singularityhub/sregistry/files/2371658/app-api-migrations.tar.gz)

**Comment by victorsndvg** [comment]
Ok, thanks again, I will report tomorrow.

**Comment by victorsndvg** [comment]
Both alternatives results in the same error.

If I delete the migrations directory I get this message on start:

```
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
worker_1  | [2018-09-12 01:54:54,037: WARNING/MainProcess] default@af888e8d04e9 ready.
uwsgi_1   | Operations to perform:
uwsgi_1   |   Apply all migrations: auth
uwsgi_1   | Running migrations:
uwsgi_1   |   No migrations to apply.
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'users'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'main'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Migrations for 'api':
uwsgi_1   |   shub/apps/api/migrations/0001_initial.py
uwsgi_1   |     - Create model ImageFile
uwsgi_1   |     - Create model ImageUpload
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'logs'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Operations to perform:
uwsgi_1   |   Apply all migrations: admin, api, auth, authtoken, contenttypes, djcelery, logs, main, sessions, social_django, taggit, users
uwsgi_1   | Running migrations:
uwsgi_1   |   No migrations to apply.
uwsgi_1   |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
uwsgi_1   |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Then, applying 'manage.py makemigrations' , and 'manage.py migrate' return the error again.

If I try to use the latest client (0.0.94) I get the follwing: 
```
[client|registry] [database|sqlite:////home/cesga/vsande/.singularity/sregistry.db]

[1. Collection return status 200 OK]
[================================] 91/91 MB - 00:00:00
Upload failed: 404 Client Error: Not Found for url: https://sregistry.srv.cesga.es/upload.
```
with this message on the server side:
```
uwsgi_1   | [pid: 96|app: 0|req: 3/3] 10.118.68.11 () {42 vars in 707 bytes} [Wed Sep 12 01:59:59 2018] POST /api/upload/chunked_upload => generated 10 bytes in 83 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
uwsgi_1   | Not Found: /upload
uwsgi_1   | [pid: 96|app: 0|req: 4/4] 10.118.68.11 () {42 vars in 775 bytes} [Wed Sep 12 02:00:02 2018] POST /upload => generated 652 bytes in 568 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on core 0)
```
If I try to manually upload a new image from web UI I also get a 404.

Any other suggestion?

Thanks!

**Comment by victorsndvg** [comment]
Hi again, 

not sure if migration is already solved, but I restored an old initial migration file containing only the "ImageFile" table like this:
```
# Generated by Django 1.11.2 on 2018-05-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import shub.apps.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('metadata', models.TextField(default='')),
                ('name', models.CharField(max_length=200)),
                ('owner_id', models.CharField(max_length=200, null=True)),
                ('datafile', models.FileField(storage=shub.apps.api.models.OverwriteStorage(), upload_to=shub.apps.api.models.get_upload_folder)),
            ],
        ),
    ]
```
then django created the file `0002_imageupload.py ` like this:
```
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import shub.apps.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(default='69d3e10d67f64f2aaf7471c31e286adb', editable=False, max_length=32, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=shub.apps.api.models.get_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
```
and the file `0003_auto_20180912_0227.py `:
```
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='upload_id',
            field=models.CharField(default='774437fabf574425a9e89d67014b8311', editable=False, max_length=32, unique=True),
        ),
    ]
```
the process returned the following:
```
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Migrations for 'api':
uwsgi_1   |   shub/apps/api/migrations/0002_imageupload.py
uwsgi_1   |     - Create model ImageUpload
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Operations to perform:
uwsgi_1   |   Apply all migrations: auth
uwsgi_1   | Running migrations:
uwsgi_1   |   No migrations to apply.
uwsgi_1   |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
uwsgi_1   |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'users'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'main'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Migrations for 'api':
uwsgi_1   |   shub/apps/api/migrations/0003_auto_20180912_0227.py
uwsgi_1   |     - Alter field upload_id on imageupload
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | No changes detected in app 'logs'
uwsgi_1   | WARNING Database disabled. Install sqlalchemy for full functionality
uwsgi_1   | Operations to perform:
uwsgi_1   |   Apply all migrations: admin, api, auth, authtoken, contenttypes, djcelery, logs, main, sessions, social_django, taggit, users
uwsgi_1   | Running migrations:
uwsgi_1   |   Applying api.0002_imageupload... OK
uwsgi_1   |   Applying api.0003_auto_20180912_0227... OK
uwsgi_1   | 
```
But it seems that `/upload` does not exists yet:
```
uwsgi_1   | [pid: 96|app: 0|req: 4/4] 10.118.68.11 () {42 vars in 707 bytes} [Wed Sep 12 02:34:59 2018] POST /api/upload/chunked_upload => generated 10 bytes in 106 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
uwsgi_1   | Not Found: /upload
uwsgi_1   | [pid: 96|app: 0|req: 5/5] 10.118.68.11 () {42 vars in 775 bytes} [Wed Sep 12 02:35:03 2018] POST /upload => generated 652 bytes in 759 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on core 0)
```
Any idea about how to solve it?

**Comment by vsoch** [comment]
Just curious - so when you upgraded you deleted your migrations directory entirely? That would be something to not do :P If you want to restore to a previous version of sregistry (one that doesn't have the upload view) you need to checkout a commit for the version before that was added. The issue above is not finding the view (which is in a newer version) and requires you to change the web sever (the nginx conf) to support that additional view.

**Comment by victorsndvg** [comment]
Thank you soooo much!

I update nginx configuration files and all run smoothly :) great!

Yep, I deleted the entire migrations directory. Thanks to the backups I was able to restore things :) ufff

Closing the issue!

**Comment by vsoch** [comment]
Phew so glad to hear! I was just about out of options and suggestions.
