### ISSUE TITLE
Upload failed: 404 Client Error

### ISSUE THREAD

**Issue by sysmso** [singularityhub/sregistry#152]
Hi
I've made an update to my registry, and now we can't upload containers anymore : 
```
sregistry push ttd.simg --name apc/ttd:latest --tag game
[client|registry] [database|sqlite:////home/ssysmso/.singularity/sregistry.db]

[1. Collection return status 200 OK]
[================================] 133/133 MB - 00:00:01
Upload failed: 404 Client Error: Not Found for url: https://sregistry.in2p3.fr/upload.

sregistry version
0.0.96
```
Our registry server is up to date, with the latest master source.

Thanks for your help.

**Comment by vsoch** [comment]
hey @sysmso ! You need to follow the instructions to update the server to use the nginx upload module. You can build the image, or use the pre-built I've provided. Instructions are here https://singularityhub.github.io/sregistry/install-server.

**Comment by sysmso** [comment]
I'm already using your nginx image : 
```
docker ps | grep nginx
219532c87648        vanessa/sregistry_nginx   "nginx -g 'daemon of…"   38 minutes ago      Up 38 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   sregistry_nginx_1
```

**Comment by sysmso** [comment]
Sorry my mistake, i've erased new nginx.conf with my old.

**Comment by sysmso** [comment]
Now i have a problem with django : 
```
sregistry push ttd.simg --name games/ttd:latest --tag game
[client|registry] [database|sqlite:////home/ssysmso/.singularity/sregistry.db]

[1. Collection return status 200 OK]
[================================] 146/146 MB - 00:00:00
Upload failed: 500 Server Error: Internal Server Error for url: https://sregistry.in2p3.fr/upload.
```

In the server's log : 

```
Internal Server Error: /api/uploads/complete/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "api_imageupload" does not exist
LINE 1: INSERT INTO "api_imageupload" ("upload_id", "file", "filenam...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "./shub/apps/api/actions/upload.py", line 110, in upload_complete
    size = size)
  File "./shub/apps/api/actions/create.py", line 113, in upload_container
    instance = ImageUpload.objects.create(file=new_path)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1063, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "api_imageupload" does not exist
LINE 1: INSERT INTO "api_imageupload" ("upload_id", "file", "filenam...

```

**Comment by vsoch** [comment]
When you update with django, if there are changes to the database models you have to do:

```
python manage.py makemigrations api
# and do that for other installed apps
```
then migrate
```
python manage.py migrate
```

**Comment by sysmso** [comment]
I have the same error... Is there an upgrade documentation for sregistry ?

```
python manage.py migrate
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, djcelery, logs, main, sessions, social_django, taggit, users
Running migrations:
  Applying api.0002_auto_20181008_1608...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "api_imageupload" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 515, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 684, in _alter_field
    params,
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "api_imageupload" does not exist

```

**Comment by vsoch** [comment]
See how @victorsndvg resolved the issue here - https://github.com/singularityhub/sregistry/issues/148 I think he wound up deleting the migrations folder, adding the ones I provided, and then updating his nginx.conf.

**Comment by sysmso** [comment]
Ok, i've deleted the migrations folder, adding the ones you provide and then do i have to run migrations commands : 
`python manage.py makemigrations api`
and
`python manage.py migrate`
?

**Comment by vsoch** [comment]
I wouldn't make them again, I would just run them without making them.

**Comment by vsoch** [comment]
You can ask @victorsndvg what he did.

**Comment by sysmso** [comment]
If i just do : 
`python manage.py migrate`
with your files, I have an error : 
```
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 114, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/code/shub/apps/api/migrations/0002_upload.py", line 8, in <module>
    import drf_chunked_upload.models
ImportError: No module named 'drf_chunked_upload'
```

**Comment by vsoch** [comment]
Ah that's a bug, I forgot to add that to be installed from requirements.txt! Let me fix that right away, and I've just shelled into my image and verified the version (and you can install this into your container):

```
django-chunked-upload==1.1.3
```
You'll need to install this into the main image (uwsgi) **and** the worker I think.

**Comment by vsoch** [comment]
Actually one sec, that might be the wrong module (I was testing two).

**Comment by vsoch** [comment]
Okay, so the requirements.txt is correct - I don't use an additional model. The reason the file is there is because I was testing it (and I gave @victorsndvg my entire folder).

**Comment by vsoch** [comment]
Django basically needs these migration files to know how to update the database. I don't know if @victorsndvg got this working, see how he generated the needed file here --> https://github.com/singularityhub/sregistry/issues/148#issuecomment-420544327 or wound up giving up and restoring to a previous version. It's bad practice on my part to change a name of a field in the database, so I apologize for that. You can always restore to a previous version if needed.

**Comment by victorsndvg** [comment]
HI @vsoch and @sysmso ,

what I did is to clean the `migrations` directory, only maintaining the initial migration (`0001_...`), and relaunch the service (`stop`, `rm` and `up`). After this step the database was in the correct status. Then, as @vsoch said, I had to update the `nginx.conf` to the latest version on the repository in order to correctly manage the `/upload` path.

I've not too much experience with django, but this is how I got it working.

Hope it helps!

**Comment by sysmso** [comment]
Ok it's working now, but i've lost all my previous images (no problem it's just test). 
What I did according to @victorsndvg : clean the migrations directory, do `python manage.py makemigrations api` then `stop`, `rm` and `up`.
Thanks four your help !

**Comment by vsoch** [comment]
phew thanks for the help @victorsndvg and @sysmso sorry for the trouble! Closing issue.
