### ISSUE TITLE
[Client] sregistry client does not respect endpoint in ~/.sregistry

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#17]
Am running an sregistry instance at `https://sregistry.randomroad.net`. In `~/.sregisty' the endpoint is correctly set (from copying out of the token page on the web interface).

```json ~/.sregistry
 { "token": "...", "username": "...", "base": "https://sregistry.randomroad.net"}
```

However, the sregistry client is still trying to use 127.0.0.1:

```python
20:44 $ sregistry push --name examples/docker docker.img
Traceback (most recent call last): 1/1 MB - 00:00:00 0/1 MB - 00:00:00
  File "/home/dave/.local/bin/sregistry", line 9, in <module>
    load_entry_point('singularity==1.2.0', 'console_scripts', 'sregistry')()
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/__init__.py", line 204, in main
    subparser=subparsers[args.command])
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/push.py", line 47, in main
    compress=not args.nocompress)
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/client/push.py", line 126, in push
    r = requests.post(url, data=monitor, headers=headers)
  File "/home/dave/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/dave/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dave/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dave/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/dave/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/dave/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/dave/.local/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /api/push/ (Caused by SSLError(CertificateError("hostname '127.0.0.1' doesn't match 'www.randomroad.net'",),))
```
Looks like the `api_base` is hard coded in `singularity/registry/client/__init__.py` and is not being overidden by the setting in `~/.sregistry`. By editing the `api_base` in the source file I can make the client talk to my server.

**Comment by vsoch** [comment]
haha, oups, yeah you are right :) Let me fix that up!

**Comment by vsoch** [comment]
okay just pushed a change to development branch! I need to make more robust testing for this stuff, thanks for helping test and debug!

**Comment by dctrud** [comment]
Tested working now here :smiley:
