### ISSUE TITLE
AttributeError: module 'django.contrib.auth.views' has no attribute 'login'

### ISSUE THREAD

**Issue by kanthsai143** [singularityhub/sregistry#176]
**Describe the bug**
AttributeError: module 'django.contrib.auth.views' has no attribute 'login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 546, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./shub/urls.py", line 52, in <module>
    plugin_urls = import_module(urls_module)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./shub/plugins/ldap_auth/urls.py", line 5, in <module>
    url(r'^login/$', auth_views.login,
AttributeError: module 'django.contrib.auth.views' has no attribute 'login'

During handling of the above exception, another exception occurred:
**To Reproduce**
Followed the instructions here to setup ldap auth. All containers are up and running 
https://singularityhub.github.io/sregistry/plugin-ldap
**Expected behavior**
I should be able to get to login page. 
If applicable, add versions and screenshots to help explain your problem.
used the docker-compose with custom database

**Comment by vsoch** [comment]
hey @kanthsai143 see https://github.com/singularityhub/sregistry/pull/177 let me know if it works for you!

**Comment by kanthsai143** [comment]
It worked!!
That was really quick. Thanks so much!

**Comment by vsoch** [comment]
awesome! I'll get this merged and released asap.
