### ISSUE TITLE
unable to connect to gcr.io

### ISSUE THREAD

**Issue by kanthsai143** [singularityhub/sregistry#178]
**Describe the bug**
unable to connect to gcr.io repo

**first  try error:**
Traceback (most recent call last):
  File "/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.1.37', 'console_scripts', 'sregistry')()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/client/__init__.py", line 368, in main
    subparser=subparsers[args.command])
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/client/pull.py", line 42, in main
    save=do_save)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/docker/pull.py", line 74, in pull
    kwargs=kwargs)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/docker/pull.py", line 118, in _pull
    file_name = self._get_storage_name(names)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/base/settings.py", line 121, in get_storage_name
    storage_folder = "%s/%s" %(self.storage, storage_folder)
AttributeError: 'Client' object has no attribute 'storage'

**Second try error** 
ERROR Your credentials are expired! Unauthorized: 401
ERROR Your credentials are expired! Unauthorized: 401

**Third try error** 
Traceback (most recent call last):
  File "/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.1.37', 'console_scripts', 'sregistry')()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/client/__init__.py", line 310, in main
    from sregistry.main import Client as cli
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/__init__.py", line 118, in <module>
    Client = get_client()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/__init__.py", line 112, in get_client
    cli = Client()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/docker/__init__.py", line 42, in __init__
    self._update_secrets()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.37-py3.6.egg/sregistry/main/docker/__init__.py", line 143, in _update_secrets
    if credentials is not None and auth is None:
UnboundLocalError: local variable 'auth' referenced before assignment

**To Reproduce**
**First try reproduce:**
gcr.io login was configured through a service account
so activated backend docker and tried to do a pull
got the following error

**second try reproduce:**
/usr/bin/pip3.6 install sregistry[google-storage]

**third try reproduce:**
/usr/bin/pip3.6 install sregistry
I have entered gcr.io credentials now
export SREGISTRY_DOCKERHUB_SECRETS=/path/config.json

**Expected behavior**
Should be able to push/pull from/to gcr.io with sregistry
If applicable, add versions and screenshots to help explain your problem.
latest versions of docker containers

**Comment by vsoch** [comment]
Did you mean to post this on https://github.com/singularityhub/sregistry-cli ? The server here wouldn't be relevant for gcr.io.

**Comment by kanthsai143** [comment]
yeah. can you move it?

**Comment by vsoch** [comment]
yep! Just wanted to check first :)
