### ISSUE TITLE
[Client] Exception when trying to push examples/centos container

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#18]
Created a container, `centos.img` by using `singularity bootstrap` on the definition in the Singularity `examples/centos` directory. This is a container bootstrapped with yum, not imported from docker. Cannot push this container to sregistry, it fails with an exception.

Pushing a container build from `examples/docker` is okay, as are other containers built from docker containers. Maybe to do with the bootstrap centos container not having a `From:` value

```bash
20:56 $ sregistry push --name examples/centos centos.img
WARNING Cannot load metadata to parse From: line.
Compressing image Traceback (most recent call last):
  File "/home/dave/.local/bin/sregistry", line 9, in <module>
    load_entry_point('singularity==1.2.0', 'console_scripts', 'sregistry')()
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/__init__.py", line 204, in main
    subparser=subparsers[args.command])
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/push.py", line 47, in main
    compress=not args.nocompress)
  File "/home/dave/.local/lib/python2.7/site-packages/singularity-1.2.0-py2.7.egg/singularity/registry/client/push.py", line 118, in push
    'datafile': (upload_to, open(upload_from, 'rb'), 'text/plain')})
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 119, in __init__
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 240, in _prepare_parts
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 488, in from_field
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 466, in coerce_data
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 529, in __init__
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 410, in encode_with
AttributeError: 'dict' object has no attribute 'encode'
```

**Comment by vsoch** [comment]
okay let me try that out.

**Comment by vsoch** [comment]
ok I changed the ordering a bit so the metadata variable read (into dict) and parse back into string is separated outside the try except loop. I can't test on ubuntu because of not having yum etc. What (I think) was happening is that metadata was being over-written, the try catch triggered when there was no from, and then it remained a dict instead of str (hence the error)

**Comment by dctrud** [comment]
Confirmed working now:

```
21:21 $ sregistry push --name examples/centos centos.img
WARNING Cannot load metadata to parse From: line.
[================================] 155/155 MB - 00:00:0055 MB - 00:00:00
Upload finished! [Return status 201 Created]
```

Container image is all good here:

https://sregistry.randomroad.net/containers/32/

**Comment by vsoch** [comment]
eggcellent!
