### ISSUE TITLE
Add authentication with local linux users. PAM auth. 

### ISSUE THREAD

**Issue by sgabenov** [singularityhub/sregistry#185]
It would be good, if there were a possibility to add authentication with local linux users, where sregistry is running. Probably the PAM auth. would be good to have.

**Comment by sgabenov** [comment]
I think this makes sense, as we have a local resources and trusted domain of users.

**Comment by vsoch** [comment]
okay - actually the management of user permissions is still a separate entity - the PAM auth module I'm adding will make it so that users on your system have accounts, but you would still need to set `USER_COLLECTIONS` to True, or manage via Teams, and the users will still need to export their tokens.

**Comment by vsoch** [comment]
hey @sgabenov I chose a module to use, and I'm having some trouble getting a user on the system logged in. I posted the issue here -> https://github.com/cnobile2012/django-pam/issues/8 along with the code - the issue might be that I'm not super familiar with PAM. If you have insight, or want to clone the branch and test, you can try it out:

```
git clone -b add/pam https://www.github.com/singularityhub/sregistry
```
I won't be able to add this for you if we can't figure it out, so hopefully the maintainer of the module can help, or you might have some insight. I'll be working on other things until I hear from you / the maintainer.

**Comment by vsoch** [comment]
Ah! Just got it working! I'll update the PR and then print out the documentation for you to follow - you will need to walk through the steps to enable the plugin, bind to your host, and then let me know if it works :) I'll ping you in a few minutes when it's ready.

**Comment by vsoch** [comment]
See https://github.com/singularityhub/sregistry/pull/186

**Comment by sgabenov** [comment]
Hi @vsoch ,
I am having some troubles with pam at the moment, and not sure if this error are related to my changes or not. I could not login with a user in passwd file amd pam_auth plugin shows this error:
```
uwsgi_1_e272b503e2b4 | Internal Server Error: /pam_auth/login/
uwsgi_1_e272b503e2b4 | Traceback (most recent call last):
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1_e272b503e2b4 |     return self.cursor.execute(sql, params)
uwsgi_1_e272b503e2b4 | psycopg2.errors.UndefinedTable: relation "users_user" does not exist
uwsgi_1_e272b503e2b4 | LINE 1: ...gree_terms", "users_user"."agree_terms_date" FROM "users_use...
uwsgi_1_e272b503e2b4 |                                                              ^
uwsgi_1_e272b503e2b4 |
uwsgi_1_e272b503e2b4 |
uwsgi_1_e272b503e2b4 | The above exception was the direct cause of the following exception:
uwsgi_1_e272b503e2b4 |
uwsgi_1_e272b503e2b4 | Traceback (most recent call last):
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1_e272b503e2b4 |     response = get_response(request)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1_e272b503e2b4 |     response = self.process_exception_by_middleware(e, request)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1_e272b503e2b4 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1_e272b503e2b4 |     return self.dispatch(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1_e272b503e2b4 |     return bound_method(*args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
uwsgi_1_e272b503e2b4 |     return view(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1_e272b503e2b4 |     return bound_method(*args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
uwsgi_1_e272b503e2b4 |     response = view_func(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1_e272b503e2b4 |     return bound_method(*args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1_e272b503e2b4 |     response = view_func(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/views.py", line 61, in dispatch
uwsgi_1_e272b503e2b4 |     return super().dispatch(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1_e272b503e2b4 |     return handler(request, *args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 141, in post
uwsgi_1_e272b503e2b4 |     if form.is_valid():
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 185, in is_valid
uwsgi_1_e272b503e2b4 |     return self.is_bound and not self.errors
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 180, in errors
uwsgi_1_e272b503e2b4 |     self.full_clean()
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 382, in full_clean
uwsgi_1_e272b503e2b4 |     self._clean_form()
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 409, in _clean_form
uwsgi_1_e272b503e2b4 |     cleaned_data = self.clean()
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/forms.py", line 196, in clean
uwsgi_1_e272b503e2b4 |     self.user_cache = authenticate(self.request, username=username, password=password)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
uwsgi_1_e272b503e2b4 |     user = backend.authenticate(request, **credentials)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/backends.py", line 20, in authenticate
uwsgi_1_e272b503e2b4 |     user = UserModel._default_manager.get_by_natural_key(username)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
uwsgi_1_e272b503e2b4 |     return self.get(**{self.model.USERNAME_FIELD: username})
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1_e272b503e2b4 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 402, in get
uwsgi_1_e272b503e2b4 |     num = len(clone)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __len__
uwsgi_1_e272b503e2b4 |     self._fetch_all()
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
uwsgi_1_e272b503e2b4 |     self._result_cache = list(self._iterable_class(self))
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
uwsgi_1_e272b503e2b4 |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
uwsgi_1_e272b503e2b4 |     cursor.execute(sql, params)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1_e272b503e2b4 |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1_e272b503e2b4 |     return executor(sql, params, many, context)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1_e272b503e2b4 |     return self.cursor.execute(sql, params)
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1_e272b503e2b4 |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1_e272b503e2b4 |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1_e272b503e2b4 |     return self.cursor.execute(sql, params)
uwsgi_1_e272b503e2b4 | django.db.utils.ProgrammingError: relation "users_user" does not exist
uwsgi_1_e272b503e2b4 | LINE 1: ...gree_terms", "users_user"."agree_terms_date" FROM "users_use...
uwsgi_1_e272b503e2b4 |

**Comment by vsoch** [comment]
It's strange that users_user doesn't exist - that's a base module that should have been there. Did you make sure to completely stop and restart the containers? Try that and running migrations? Shell inside and do:

```bash
$ python manage.py makemigrations admin
$ python manage.py makemigrations users
```
I haven't seen this issue but it seems like something was not updated in the database that needed to be.

**Comment by vsoch** [comment]
It would also be helpful if you could clearly walk me through the steps that led to this. I can't read minds, unfortunately.

**Comment by sgabenov** [comment]
Of course. So overall what i am trying to do: i try to use pam plugin to authenticate users. But the passwd is located in NIS database, so i have to install rpcbind and nis services into vanessa/sregistry container and rebuild it. I am able use PAM inside the container ("id test1") and get a user pid. But when i try to login through web it raises this errors.
I think it will be more helpful if i could share the Dockerfile i am using to build the container.

**Comment by sgabenov** [comment]
```
diff --git a/Dockerfile b/Dockerfile
index d7628a3..0ae833b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,6 +2,10 @@ FROM python:3.5.7
 ENV PYTHONUNBUFFERED 1
 ENV DEBIAN_FRONTEND noninteractive

+# Add proxy
+ENV http_proxy http://nibr-proxy.global.nibr.novartis.net:2011
+ENV https_proxy http://nibr-proxy.global.nibr.novartis.net:2011
+
 ################################################################################
 # CORE
 # Do not modify this section
@@ -32,6 +36,15 @@ RUN apt-get update && apt-get install -y \
     squashfs-tools \
     build-essential

+RUN apt-get update && apt-get install -y \
+    mc \
+    nis
+
+# Configure NIS
+COPY ./nis/yp.conf ./nis/nsswitch.conf /etc/
+RUN chmod 755 /etc/yp.conf /etc/nsswitch.conf
+
+
 # Install Singularity
 RUN git clone -b vault/release-2.5 https://www.github.com/sylabs/singularity.git
 WORKDIR singularity
@@ -49,11 +62,10 @@ ADD . /code/
 # You are free to comment out those plugins that you don't want to use

 # Install LDAP (uncomment if wanted)
-# RUN pip install python3-ldap
-# RUN pip install django-auth-ldap
+RUN pip install python3-ldap django-auth-ldap sqlalchemy

 # Install PAM Authentication (uncomment if wanted)
-# RUN pip install django-pam
+RUN pip install django-pam

 # Install Globus (uncomment if wanted)
 # RUN /bin/bash /code/scripts/globus/globus-install.sh
@@ -83,6 +95,7 @@ RUN rm /code/cronjob
 # Create hashed temporary upload locations
 RUN mkdir -p /var/www/images/_upload/{0..9} && chmod 777 -R /var/www/images/_upload

+# Additional services are added in run_uwsgi. NIS and rpcbind.
 CMD /code/run_uwsgi.sh

 EXPOSE 3031
```

**Comment by sgabenov** [comment]
Also, when i build a container, there are erros during the start:
1. Some errors, asking to get module sqlalchemy
2.
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E007) The custom handler404 view 'shub.apps.base.views.errors.handler404' does not take the correct number of arguments (request, exception).
```

**Comment by vsoch** [comment]
Why don't you instead try to use the docker container as a base? It sounds like you are overwriting something.

**Comment by vsoch** [comment]
Also it's really hard to read that Dockerfile, it's not useful to help.

**Comment by vsoch** [comment]
If you need to get something in the container from the host, you'd be better to bind it from the host instead of copy,

**Comment by vsoch** [comment]
You don't need sqlalchemy for sregistry server, I know for a fact the message you are getting is a warning :)

**Comment by sgabenov** [comment]
ok, i'll try to do the install from the scratch, thank you. Will reply if i face the same errors

**Comment by vsoch** [comment]
Yes, what you want to do is try the docker-compose application *without making changes* to first ensure it's working properly. Once that's the case, then you can build an image using vanessa/sregistry:<some tag> as base, and test commands interactively in the image. Making a ton of commands that produce even more error messages without having a clean base is just going to be hard and confusing.

**Comment by vsoch** [comment]
I'd first like you to try and reproduce the 404 page issue from a fresh install. We can fix that first. I just tried but I wasn't able to get the message.

**Comment by vsoch** [comment]
I'm going to do a PR to fix the message level of the sregistry client so the warning isn't issued (it's not helpful). I'll also update the 404 and 500 handler to have the exception argument, and we can test to see if this helps you.

**Comment by vsoch** [comment]
I started a PR here to quiet the warnings: https://github.com/singularityhub/sregistry/pull/188

I tried changing the custom handlers for 404 and 500 to what was suggested by your error, and this produced the error on my end :) So I'll wait for your instruction for how you produced this. I have a call now so I'll be away for t a bit.

**Comment by sgabenov** [comment]
Hi @vsoch,
I tried to run everything from the scratch and use only your image. Looks like errors are related to not able to execute "makemigrations" script.
```
[root@test-vm1 sregistry]# docker exec -it sregistry_uwsgi_1_6d6ab3b497bf bash
root@0aaa1a546026:/code#
root@0aaa1a546026:/code#
root@0aaa1a546026:/code# python manage.py makemigrations admin
WARNING Database disabled. Install sqlalchemy for full functionality
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E007) The custom handler404 view 'shub.apps.base.views.errors.handler404' does not take the correct number of arguments (request, exception).
root@0aaa1a546026:/code# python manage.py makemigrations users
WARNING Database disabled. Install sqlalchemy for full functionality
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E007) The custom handler404 view 'shub.apps.base.views.errors.handler404' does not take the correct number of arguments (request, exception).
root@0aaa1a546026:/code#
```

**Comment by vsoch** [comment]
You need to test from the image that I've provided in the PR - the one you are showing above cannot be the correct version because I still see the 

```
WARNING Database disabled. Install sqlalchemy for full functionality
```
You need to remove all images:

```
docker-compose stop
docker-compose rm
```
And then pull the code from the branch of the PR.

Wait, so you are saying it works now?

**Comment by vsoch** [comment]
If you need to rebuild the recipe (to silence the warnings)

```bash
$ docker build -t vanessa/sregistry .
```
from the base of the repository.

**Comment by sgabenov** [comment]
Yep, it is working. And also with small modifications (add rpcbind and nis apt packages) i was able to authenticate with NIS users. It is good for me now, thank you once again.
