### ISSUE TITLE
unable to install sregistry-cli

### ISSUE THREAD

**Issue by ashwinidr3** [singularityhub/sregistry#246]
Download error on https://pypi.org/simple/pytest-runner/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    entry_points = {'console_scripts': ['sregistry=sregistry.client:main']})
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

**To Reproduce**
python setup.py install

**Expected behavior**

i am using python version 3.7.4
singularity version - 3.4
i have sregitry installed and configured, trying to connect to the server by creating remote enpoint by installing sregitry-cli and i bump into this error. i even tried to change the python version. but same result .

**Comment by vsoch** [comment]
This is the same issue as you reported previously – your SSL is not configured correctly and likely is missing a base library. This is outside of the scope of what is an issue with the Sregistry Client.
