### ISSUE TITLE
Docker-compose is not working

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#28]
Docker-compose is not working. 

vanessa/sregistry does not exists in docker hub.

**Comment by vsoch** [comment]
I forgot to add it :)

https://hub.docker.com/r/vanessa/sregistry/

Give it a go now!

**Comment by victorsndvg** [comment]
Thanks @vsoch ,

now docker-compose does not crash... but I'm not able to make it work.
It seems that all services ar up and running except the worker:
```
5e6e6509a8eb        vanessa/sregistry   "celery worker -A shu"   5 minutes ago       Exited (1) 3 minutes ago                            sregistry_worker_1
ac40b9d52d93        nginx               "nginx -g 'daemon off"   58 minutes ago      Up 6 minutes               0.0.0.0:80->80/tcp       sregistry_nginx_1
c3e7bb653c7e        vanessa/sregistry   "/bin/sh -c /code/run"   58 minutes ago      Up 6 minutes               3031/tcp                 sregistry_uwsgi_1
977c7d599b44        postgres            "docker-entrypoint.sh"   58 minutes ago      Up 6 minutes               5432/tcp                 sregistry_db_1
6ec8d500d08a        redis:latest        "docker-entrypoint.sh"   58 minutes ago      Up 6 minutes               0.0.0.0:6379->6379/tcp   sregistry_redis_1
```
Taking a look to worker logs ( `$ docker logs  sregistry_worker_1`) I see that it is failing:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/usr/local/lib/python3.5/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/usr/local/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.5/site-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/usr/local/lib/python3.5/site-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/usr/local/lib/python3.5/site-packages/celery/app/base.py", line 330, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 252, in autodiscover_tasks
    related_name) if mod)
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 273, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 273, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.5/site-packages/celery/loaders/base.py", line 295, in find_related_module
    _imp.find_module(related_name, pkg_path)
  File "/usr/local/lib/python3.5/imp.py", line 270, in find_module
    "not {}".format(type(name)))
RuntimeError: 'list' must be None or a list, not <class 'str'>
```

I'm trying to follow your instructions, but I'm not able to make it running.

Any recommendation?

Thanks!

**Comment by vsoch** [comment]
ah I've seen this error - one of the apps is missing __init__.py I think. See here --> https://stackoverflow.com/questions/35838989/runtimeerror-list-must-be-none-or-a-list-not-class-str-while-trying-to-s could you poke through the folders and let me know if there is one missing? I must have forgotten to add it.

**Comment by vsoch** [comment]
I think if you shell into the image and try to load the tasks module from each respective app, the error will reveal. Eg:

```
docker exec -it c3e7bb653c7e  bash
python manage.py shell
from shub.apps.api.tasks import *
from shub.apps.singularity import *
```
It might be a version issue or something like that. Let me know and I'll update the image.

**Comment by dctrud** [comment]
Hi @vsoch -  `shub/apps/logs/__init__.py` is missing. Adding that will get you past the error above. Then you'll get:

```
ImportError: No module named 'shub.apps.singularity.tasks'
```

Which this will fix:

``` diff
index 7c6dc42..db8d177 100644
--- a/shub/settings/tasks.py
+++ b/shub/settings/tasks.py
@@ -47,8 +47,7 @@ CELERY_DEFAULT_QUEUE = 'default'
 CELERY_QUEUES = (
     Queue('default', Exchange('default'), routing_key='default'),
 )
-CELERY_IMPORTS = ('shub.apps.api.tasks',
-                  'shub.apps.singularity.tasks',)
+CELERY_IMPORTS = ('shub.apps.api.tasks',)

 CELERY_RESULT_BACKEND = 'redis://%s:%d/%d' %(REDIS_HOST,REDIS_PORT,REDIS_DB)
```

**Comment by dctrud** [comment]
Trivial PR is linked: https://github.com/singularityhub/sregistry/pull/29

**Comment by vsoch** [comment]
Thanks for the team work on this! I strangely didn't have the __init__.py missing for logs, but the worker tasks for singularity missing makes sense (I have them locally testing some things and didn't update or remove)

**Comment by victorsndvg** [comment]
Thanks! the web interface is working like a rocket! I'm going to play with it.

**Comment by vsoch** [comment]
Awesome!! :rocket:
