### ISSUE TITLE
Pre-built image on quay using wrong djangorestframework version

### ISSUE THREAD

**Issue by JossWhittle** [singularityhub/sregistry#362]
**Describe the bug**

Related to #266. The pre-built quay.io/vanessa/sregistry image does not seem to have the pinned version of the djangorestframework. Building the image locally is stated as optional in the installation docs but is required to properly execute the management utilities. 

**To Reproduce**

```
git clone https://github.com/singularityhub/sregistry.git --depth 1 --branch v1.1.31 --single-branch

# Add config.py, secret.py, ect ... 

docker-compose up -d

# Pulls images from quay

NAME=$(docker ps -aqf "name=sregistry_uwsgi_1")
docker exec $NAME python /code/manage.py add_superuser --username somesuperuser
```

```
Traceback (most recent call last):
  File "/code/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/code/shub/urls.py", line 17, in <module>
    from shub.apps.api import urls as api_urls
  File "/code/shub/apps/api/urls/__init__.py", line 2, in <module>
    from .routers import urlpatterns as routers
  File "/code/shub/apps/api/urls/routers.py", line 21, in <module>
    router.register(r"^containers", ContainerViewSet, base_name="container")
TypeError: register() got an unexpected keyword argument 'base_name'
```

**Expected behavior**

```
docker-compose down

docker build -t quay.io/vanessa/sregistry .

docker-compose up -d

NAME=$(docker ps -aqf "name=sregistry_uwsgi_1")
docker exec $NAME python /code/manage.py add_superuser --username somesuperuser

# Succeeds!
```

**Comment by vsoch** [comment]
That would make sense, it's sort of assumed that the user will just clone master, but if the clone is to a release, the release should use the matching tag. I can use this convention going forward.

**Comment by vsoch** [comment]
@JossWhittle please see https://github.com/singularityhub/sregistry/pull/363. Instead of pinning versions in the docker-compose (which is hard to maintain) I added a section to the docs, and comments alongside the image names. When you get a chance could you please test? When we merge that PR there will be a container build and deploy to quay, and I can also draft a release here.

**Comment by JossWhittle** [comment]
@vsoch sorry for the delayed response. All working now by modifying the docker-compose to use the correct images. Thank you for the assistance in debugging.

**Comment by vsoch** [comment]
Sure thing! So the bump in Python in the base images is A-ok?

**Comment by vsoch** [comment]
Ping @JossWhittle did you get a chance to review the PR for this issue?

**Comment by JossWhittle** [comment]
The PR branch spins up correctly through docker-compose using the new python version, but this isn't a test using a fully configured installation. 

I'm still using v1.1.31 in production currently by changing the compose file for version pinning and adding traefik for SSL.
